### ISSUE TITLE
Already out of date

### ISSUE THREAD

**Issue by EwoutH** [arc53/llm-price-compass#9]
Interesting project, but unfortunately, it's already out of date. For example, Deepinfra dropped their prices to $0.35 / $0.40 for a million input/output tokens.

For such a thing to be useful, it's important it can be relied upon to be up to date. Does this repo update it's data automatically?

**Comment by dartpain** [comment]
Thank you for noting it, I pushed an update.
Currently I am more focused on finding most optimal inference strategy. Will publish some new cool results with SGlang soon.

If there is some simple way to automate those numbers for managed providers please suggest an option. Otherwise we will have to manually review it.
